In [1]:
import numpy as np
print('Biblioteka Numpy została zaimportowana jako np.')

Biblioteka Numpy została zaimportowana jako np.


In [11]:
#utworzenie listy
moje_dane = [10,20,30,40,50,60,70,80]
#przekształcenie listy w tablicę
moje_dane = np.array(moje_dane)
#wyświetlenie tablicy
print(moje_dane)
#sprawdzenie typu danych
print(f'Dtype: {moje_dane.dtype}')
#sprawdzenie formy tablicy (8 elementów)
print(f'Shape: {moje_dane.shape}')
#Wyświetlenie elementu o indexie 2
print(moje_dane[2])
#Wyświetlenie elemntów od indexu 5 do końca
print(moje_dane[5: ])
#Wyświetlenie co drugiego elemntu zaczynając od indeksowanego 1
print(moje_dane[1: :2])
#Przekształcenie tablicy w dwuwymiarową 4 wiersze po 2 kolumny
print(f'{moje_dane.reshape(4,2)}')

[10 20 30 40 50 60 70 80]
Dtype: int64
Shape: (8,)
30
[60 70 80]
[20 40 60 80]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
