In [1]:
import numpy as np
print('Biblioteka Numpy została zaimportowana jako np.')

Biblioteka Numpy została zaimportowana jako np.


In [11]:
#utworzenie listy
moje_dane = [10,20,30,40,50,60,70,80]
#przekształcenie listy w tablicę
moje_dane = np.array(moje_dane)
#wyświetlenie tablicy
print(moje_dane)
#sprawdzenie typu danych
print(f'Dtype: {moje_dane.dtype}')
#sprawdzenie formy tablicy (8 elementów)
print(f'Shape: {moje_dane.shape}')
#Wyświetlenie elementu o indexie 2
print(moje_dane[2])
#Wyświetlenie elemntów od indexu 5 do końca
print(moje_dane[5: ])
#Wyświetlenie co drugiego elemntu zaczynając od indeksowanego 1
print(moje_dane[1: :2])
#Przekształcenie tablicy w dwuwymiarową 4 wiersze po 2 kolumny
print(f'{moje_dane.reshape(4,2)}')

[10 20 30 40 50 60 70 80]
Dtype: int64
Shape: (8,)
30
[60 70 80]
[20 40 60 80]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [12]:
#Utworzenie 2 tablic
wektor1 = np.array([1,2,3,4])
wektor2 = np.array([5,6,7,8])
#wykonanie mnożenia na tablicach
print(wektor1*wektor2)
#Dodawanie na tablicach
print(wektor1+wektor2)

[ 5 12 21 32]
[ 6  8 10 12]


In [13]:
#Utworzenie tablicy
liczby_do_potegi = np.array([2,3,4])
#Podniesienie elementów tablicy do 3 potęgi
print(liczby_do_potegi**3)

[ 8 27 64]


In [21]:
#Utworzenie tablicy
temperatury = np.array([22,25,18,30,20,23])
#Wyświetlenie temperatur wyższych niż 22
print(f'{temperatury[temperatury > 22]}')
#Wyświetlenie najwyższej temperatury
print(f'{temperatury.max()}')
#Wyświetlenie najniższej temperatury
print(f'{temperatury.min()}')
#Obliczenie średniej temperatury na podstawie danych z tablicy
print(f'{temperatury.mean()}')

[25 30 23]
30
18
23.0
